### ISSUE TITLE
FSI object not found when running from .NET Interactive notebook

### ISSUE THREAD

**Issue by mabasic** [ronaldschlenker/FsHttp#70]
It all works, but I get this message in the output:

```
--- FsHttp: running in FSI - Try registering printer...
--- FsHttp: FSI object not found.
```

When I run the same code from FSI it outputs:

```
--- FsHttp: running in FSI - Try registering printer...
--- FsHttp: Printer successfully registered.
```

Is this something that can be improved or is it normal behavior ?

**Comment by ronaldschlenker** [comment]
For notebooks, we need a custom formatter, which is explained in [this blog post](https://www.gregorbeyerle.me/posts/2020/11/30/writing-formatters-for-dotnet-interactive).

In the `Microsoft.DotNet.Interactive.AspNetCore` package [here](https://www.nuget.org/packages/Microsoft.DotNet.Interactive.AspNetCore), there's something similar for the .Net HttpRequest and HttpResponse.

Since FsHttp is wrapping (copying) the underlying .Net HTTP objects, we can't reuse them. Solutions could be:

* Write an own custom formatter and make a new package for interactive notebooks
* Expose the underlyuing HttpRequest and HttpResponse objects and use the formatting from the aspnetcore package.

**Comment by mabasic** [comment]
How difficult is it to do this "Expose the underlyuing HttpRequest and HttpResponse objects and use the formatting from the aspnetcore package."?

I will need to read the link you sent before continuing this conversation :)

**Comment by ronaldschlenker** [comment]
I published preview4, which exposes the original HttpRequestMessage (which I think is a good thing anyway because I see FsHttp as a lightweight API that doesn't hide too much).

Could you test the following:

```fsharp
#r "nuget: SchlenkR.FsHttp, 6.0.0-preview4"

// I guess referencing is enough to get the formatters registered?
#r "nuget: Microsoft.DotNet.Interactive.AspNetCore, 1.0.0-beta.21459.1"

open FsHttp
open FsHttp.DslCE
open FsHttp.Operators

// After this, the output formatter for HttpResponseMEssage should trigger.
% get "https://www.wikipedia.de"
|> Response.httpResponseMessage
```

BTW, the code that implements the formatter for `HttpResponseMessage` can be [found here](https://github.com/dotnet/interactive/blob/54c98c456b7afeba45c599cba8aae4134a97c81e/src/Microsoft.DotNet.Interactive.AspNetCore/HttpClientFormatter.cs).

**Comment by mabasic** [comment]
I still get this:

```
--- FsHttp: running in FSI - Try registering printer...
--- FsHttp: FSI object not found.
```

but I also get this:

![Screenshot (31)](https://user-images.githubusercontent.com/1839930/132988186-cf5e9f4c-0fd4-4c06-8a4a-a2c1836f9b48.png)
![Screenshot (32)](https://user-images.githubusercontent.com/1839930/132988188-49cea975-091b-4125-87a8-f63bfbcc3d21.png)

**Comment by ronaldschlenker** [comment]
I can confirm that - in the latest version of .Net Interactive Notebooks, there seems to be no need for referencing `Microsoft.DotNet.Interactive.AspNetCore`. The message appears - that's correct.
